[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "data",
    "DjangoApp/news/migrations",
]


line-length = 79
indent-width = 4


[tool.ruff.lint]

select = ["E4", "E7", "E9", "F", "N", "DJ","Q"]
ignore = ["Q000","Q003"]


fixable = ["ALL"]
unfixable = []


[tool.ruff.format]

quote-style = "single"

indent-style = "space"
