# Generated by Django 5.1.5 on 2025-02-02 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(help_text='Список адресатов (через запятую)')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=255)),
                ('message', models.TextField(help_text='Текст сообщения')),
                ('send_at', models.DateTimeField(help_text='Время отправки')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
